# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='code')),
                ('adresse', models.CharField(max_length=120, verbose_name='adresse')),
                ('commentaire', models.TextField(verbose_name='commentaire')),
            ],
        ),
    ]
